file.go
file_test.go

I left out testing downloading commits and branches from private repos in my test cases and sure enough those failed whereas their public equivalent succeeded.
This fixes those issues and adds additional tests to validate this as well.

Fetch was not downloading commits or branches from private repos.

---

_ci/build-and-push-release-assets.sh
circle.yml

This PR adds a script and updates circle.yml so that every time we create a new release, the CircleCI job builds new binaries and uploads them to that release.

Automatically build binaries for new releases

---

README.md
fetch_error.go
github.go
github_test.go
main.go

This PR allows fetch to download not only source files from GitHub repos, but also binary files from GitHub releases. It’s easy to download a release asset from a public repo, as you can just `wget` the URL, but for private repos, it’s a confusing, painful, multi-step process that involves making several API calls. There is an [SO thread about it](http://stackoverflow.com/a/35280061/483528) which would probably love to hear that `fetch` makes this an easy one-step process.
As part of this PR, I’ve also made a few other tweaks:
1. Added support to fetch to read the GITHUB_OAUTH_TOKEN from an env var, which is much safer than as a command line option.
1. Instead of a filter passed as a command-line arg, you can now specify one or more paths to download from the source code using the …

Release asset

---

tag.go
tag_test.go

OK @brikis98 this should do it. Apologies for the changes and clutter regarding the indents ... :/
**Test output before change:**
```
--- FAIL: TestGetLatestAcceptableTagNoSuchTag (0.00s)
tag_test.go:137: Expected 'Tag does not exist' but received nothing
FAIL
coverage: 49.4% of statements
exit status 1
FAIL    _/home/src      8.597s
```
**Test output after change:**
```
PASS
coverage: 50.2% of statements
ok      _/home/src      8.482s
```
Let me know if there is anything else needed!

added fix and test for issue #6

---

README.md
checksum_test.go
github.go
github_test.go
main.go

Fetch seems like a much more enjoyable way to fetch release artifacts from GitHub on the command line. More enjoyable then writing a curl script and more reusable. 
However, I'm working with repos in both GitHub Enterprise (GHE) and GitHub.com. These changes make it so that I can pass in the URLs (base and api) of the GHE instance that I'm working with and be able to fetch artifacts from there.
I did some basic smoke testing on this. I was able to fetch from GHE. I can add/fix tests if it's required for merge, it just won't be until tomorrow.

support github enterprise by allowing custom api and base urls

---

main.go

github.com/codegangsta/cli has moved to gopkg.in/urfave/cli.v1. Github is automatically redirecting requests to codegangsta, but it is recommended to update the references.

Update dependency reference 

---

README.md
checksum.go
checksum_test.go
github.go
main.go
main_test.go

~**Caveat**: The checksum functionality for verifying release assets still only supports 1 asset. If multiple assets match the regex provided, an error will be returned.~
Multiple checksums can now be passed via the command line and the downloaded assets must match one of them.

Use regex for release asset download

---

Gopkg.lock
file.go
file_test.go
github.go
github_test.go
main.go

Fixes #48. This is a tricky one to test because we don't have a running instance of GitHub Enterprise against which we can run integration tests. So the best we can do is to validate that the URL fetch attempts to download from in the case of GitHub Enterprise is as expected.
I also noticed a few areas where errors were being swallowed so I added some boilerplate error handling code for those cases. 
In the end, for the +178 lines of code additions here, the actual bug fix just 4 lines of code.

Enable asset downloads from GitHub Enterprise

---

main.go
main_test.go

Please review my PR with changes to fix issue #31.
The issue mentions that an incorrect error is reported on supplying empty value to option --branch. But the same issue can happen when an empty value is supplied to any of the other options. This PR fixes the issue for all options.
I modified the parseOptions() function to return an additional value for error. I felt this resulted in least complicated code.

Check and report error on empty option values

---

Gopkg.lock
Gopkg.toml
README.md
checksum_test.go
github.go
github_test.go
main.go
main_test.go

This PR fixes issue issue https://github.com/gruntwork-io/fetch/issues/45
Progress on file download makes downloading large files much easier as feedback
is given once per second now.

Add progress to file download

---

README.md

- Added description for installing fetch using homebrew, available after https://github.com/Homebrew/homebrew-core/pull/59049 was merged.

Add package manager install process on docs

---

.circleci/config.yml

This repo was using a custom set of credentials for Phx DevOps and our GitHub machine user. I've removed those creds from the CircleCi config and here am switching the repo to use [CircleCi Contexts](https://circleci.com/docs/2.0/contexts) instead.

Add CircleCi Context

---

file.go
file_test.go
main.go

This closes #39 
The route I took here was to just show the non-directory file count every time; if you'd prefer that I follow the letter of the issue and only print when the number of files is zero, I can make that change.
I also did a minor "look and feel" by pluralizing the wording, I think it's a nice touch, but it does add a bit of extra code (no ternary operator in golang), so I'm happy to change that if desired, too.

Show file count on zip extraction

---

github.go
github_test.go

This closes #75 
I validated each tag, discarding any that aren't SemVer.
For testing, I suggest that a non-SemVer tag be added to the public and private test repositories `github_test.go`.
https://github.com/gruntwork-io/fetch/blob/4bec67f9ab28423e6b6f72b2fc9d397e5681c671/github_test.go#L25-L28

Skip tags that are not Semantically Versioned

---

.circleci/config.yml

We've decided to delete all "nightly" or triggered jobs as they are incompatible with circleci contexts.

Delete circleci nightly job

---

.gitignore
github.go
github_test.go

This is https://github.com/gruntwork-io/fetch/pull/83 re-opened with some minor clean up. This should fix #26 and #46. Thank you to @m-bal for doing most of the work!

Add support for pagination

---

main.go

`--ref` takes lower precedence than the other flags.
This documentation change reflects reality.

Document the precedence of --ref properly

---

.circleci/config.yml

Update to the latest base image, which has a newer version of Go, and a newer version of our `build-go-binaries` script. This supports building fetch for Darwin/ARM, which hopefully fixes #82.

Update CircleCi base image

---

github_test.go
main.go
main_test.go

Handle situations where the release asset name contains regex symbols that could mess up matching.
Please ensure all of these TODOs are completed before asking for a review.
Fixes #93

Perform direct asset name comparison

---

integration_test.go
main.go

An initial stab at supporting sending the contents of a downloaded asset to standard output
Please ensure all of these TODOs are completed before asking for a review.
Addresses #101

Output release asset contents to standard output

---

main.go
main_test.go

Updated logic of release asset downloading to throw an error if release is not found
Please ensure all of these TODOs are completed before asking for a review.
Fixes https://github.com/gruntwork-io/gruntwork-installer/issues/79

Return error if release tag is not found
